# Program for demonstrating Random Access File

try:
    with open("info.data","r") as fp:
        print("---------------------------")
        print("Initial Position of fp=",fp.tell())
        fd=fp.read(5)
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
        fd = fp.read(4)
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
        fd = fp.read(7)
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
        fd=fp.read()
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
        fd = fp.read()
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
        fp.seek(0)
        print("---------------------------")
        fd = fp.read(2)
        print(fd)
        print("Now Position of fp=", fp.tell())
        print("---------------------------")
except FileNotFoundError:
    print("File Does not Exist")
