a = int(input("Enter Value of a: "))
b = int(input("Enter Value of b: "))
print("*"*50)
print("\tResult of Arithmetic Operators")
print("*"*50)
print("\tSum({},{})={}".format(a,b,a+b))
print("\tSub({},{})={}".format(a,b,a-b))
print("\tMul({},{})={}".format(a,b,a*b))
print("\tDiv({},{})={}".format(a,b,a/b))
print("\tFloor({},{})={}".format(a,b,a//b))
print("\tModDiv({},{})={}".format(a,b,a%b))
print("\tPower({},{})={}".format(a,b,a**b))
print("*"*50)